[package]
name = "takkit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
takparse = "0.6.0"

[dev-dependencies]
rstest = "0.18.2"

[profile.dev-fast]
inherits = "release"
debug-assertions = true
overflow-checks = true
